= ranch:get_transport_options(3)

== Name

ranch:get_transport_options - Get the current transport options

== Description

[source,erlang]
----
get_transport_options(Ref :: ranch:ref())
    -> TransOpts :: ranch:transport_opts(any())
----

Get the current transport options.

== Arguments

Ref::

The listener name.

== Return value

The current transport options are returned.

If the transport options were specified as only socket options (not a map) using
link:man:ranch:start_listener(3)[ranch:start_listener(3)] or
link:man:ranch:set_transport_options(3)[ranch:set_transport_options(3)], they
are returned as `#{socket_opts => SocketOpts}`.

== Examples

.Get the current transport options
[source,erlang]
----
TransOpts = ranch:get_transport_options(example).
----

== See also

link:man:ranch:get_max_connections(3)[ranch:get_max_connections(3)],
link:man:ranch:get_protocol_options(3)[ranch:get_protocol_options(3)],
link:man:ranch:set_transport_options(3)[ranch:set_transport_options(3)],
link:man:ranch(3)[ranch(3)]
