## Use workflows from ninenines/ci.erlang.mk to test Ranch.

name: Check Ranch

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
      ## Every Monday at 4am.
      - cron: 0 4 * * 1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    uses: ninenines/ci.erlang.mk/.github/workflows/ci.yaml@master
